### ISSUE TITLE
Where is I.Expect.Alert in v2?

### ISSUE THREAD

**Issue by jptillman** [stirno/FluentAutomation#66] opened 2012-11-05 19:34 UTC
I'm using the Selenium WebDriver support with FluentAutomation.  How do we capture/handle javascript popups?  I saw some references on the web to I.Expect.Alert(), but I guess that's probably v1?

The "docs," by the way, could use some love.  Either they are quite incomplete, or this library has a long way to go before it's really useful.

**Comment by stirno** [comment] 2012-11-05 20:12
The v1 functionality for alerts was somewhat unreliable so we're looking at re-implementation with a better API. Its on the list for the 2.1 release but is currently lower priority, given the relatively low occurrence of alert/confirm dialogs in modern apps. Is this something you encounter regularly in applications you are automating?

As to the documentation, its a start. I'd love any comments/feedback on what you would like to see in the docs. Also, we would gladly accept user assistance in expanding our docs and examples.

**Comment by jptillman** [comment] 2012-11-06 18:36
I was suspecting that the feature was "in transition" based on what I saw in the lineage of the docs and code.  I try to avoid using alert(), et al, myself, but we do have a few in an app I'm trying to test.  The main problem is that it's something of a showstopper, because once that dialog pops up, nothing's going to happen until it's cleared, and my test can't assume there's a dialog box because that assumes the test succeeded.

If we start using Fluent Automation, I'd be willing to help with docs.  I'll let you know if we do and will try to assist.  In the meantime, having at least something that would detect a modal alert box has been raised would be useful.

**Comment by jptillman** [comment] 2012-11-06 19:21
As a workaround, is there a way I can access to the lower-level WebDriver or some other part of the Selenium library so that I can use its ability to work with the popup?

**Comment by 0liver** [comment] 2012-12-07 15:29
You can access the IWebDriver used by Selenium in the following way:

```
[TestFixture]
public class FormTest : FluentTest {
    public FormTest() {
        SeleniumWebDriver.Bootstrap();
    }

    [SetUp]
    public void Setup() {
        I.Wait(1); // need to initialize `I` to set up the Container
        Console.WriteLine(Container.Resolve<IWebDriver>().GetType().FullName);          
    }
}
```

This will then be either a FirefoxDriver, ChromeDriver, or IEDriverWrapper instance, depending on the (optional) argument to the `Bootstrap()` method.

**Comment by iblazhev** [comment] 2012-12-20 14:28
Hi @0liver , I tried your solution but it creates a new instance of the webdriver with a new browser launched, it doesn't return the old instance.

**Comment by 0liver** [comment] 2012-12-20 22:04
@abuseukk: Sorry to hear that. I hadn't tried the code I posted above but it surprises me that it would behave that way. Anyway, looks like one of the developers will need to clarify this issue.

**Comment by stirno** [comment] 2012-12-30 17:25
Hey guys, sorry I havent responded to this yet. Been on a much needed vacation away from all things code. :)

You're correct that resolving a new WebDriver instance (or our wrapper class for that matter) will in fact get you a second browser, rather than the expected current instance.

I've been debating providing access to the underlying automation for some time. In the past its seemed like doing so would lessen the feedback we get from users to help us identify where we need to improve the abstraction. Now, I see it as a way to provide users what they need when we are still working on the cross-provider abstractions.

To remedy this, I have been working on some changes to essentially allow the method @0liver suggested here. The instances registered inside the bootstrap blocks would behave as singletons and the user could provide access to this via their own mechanisms after the constructor or a Setup method.

I'd expect this to hit GitHub in the next week or so, NuGet shortly after that.

**Comment by kravasb** [comment] 2013-07-02 11:46
My teammate suggested a workaround for that issue:

<pre>
<code>public YourConstructor()
        {
            SeleniumWebDriver.Bootstrap(SeleniumWebDriver.Browser.Chrome);
            var previous = Settings.Registration;
            Settings.Registration = container =>
                                                {
                                                    previous(container);
                                                    container.Register<IWebDriver, ChromeDriver>().AsSingleton();
                                                };
        }</code>
</pre>

After such manipulations you can use something like this to handle your alerts:

<pre>
<code>
var webDriver = Container.Resolve<IWebDriver>();
var alert = webDriver.SwitchTo().Alert();
alert.Accept();
</code>
</pre>

**Comment by stirno** [comment] 2014-03-28 19:58
v3.0 just got a proper implementation of alert handling again... has issues in WatiN because.. well.. WatiN has issues in that area, but its working great in Selenium in testing.

Related calls for alerts/prompts:

```
I.Click(Alert.OK);
I.Click(Alert.Cancel);

I.Expect("Whats up doc?").In(Alert.Message);
I.Enter("Text").In(Alert.Input);
```

**Comment by LSTANCZYK** [comment] 2014-03-28 21:24
This is awsome!

**Comment by stirno** [comment] 2014-03-28 22:33
Confirmed working as best as we can right now in the 3.0 branch (fixmultibrowsertesting -- stupid name I know..). Should be up on NuGet in a few days.

**Closed as completed by stirno** 2014-03-28 22:33 UTC
